### ISSUE TITLE
[Bug] Error message: "Failed to start game" after loading game and core files on Amiga and Mame 2003 games

### ISSUE THREAD

**Issue by shaylevary** [EmulatorJS/EmulatorJS#1030]
After installing version 4.2.2, I encountered an error message saying "Failed to start game" when attempting to run Amiga games or MAME2003 games such as Operation Wolf. The error appears on bottom of the screen after the game and core files are loaded.

I was able to resolve the issue only by reverting to older Core files. For example, in the case of MAME2003, switching to the mame2003-wasm.data file dated 07-01-25 solved the problem.

Regarding Amiga games, I have already been using an older Core version for quite some time — specifically, the puae-wasm.data file dated 19-08-24 — since newer versions had issues with unresponsive keys (either arrow keys or action keys, I don’t recall exactly which).

nyway, the new version of the Amiga core does not work at all and displays the error message Failed to start game", as previously mentioned.

I have attached a copy of the console log generated when attempting to run an Amiga game, for your reference.

[Amiga-Console_error_messages.txt](https://github.com/user-attachments/files/20762754/Amiga-Console_error_messages.txt)

I tested PSX, C64, and N64 games, and they all appear to function correctly.

**Comment by ethanaobrien** [comment]
Amiga error appears to be specific to WHDLoad roms

Does mame2003_plus have this same issue? Are all games dead on mame2003 core?

**Comment by shaylevary** [comment]
In MAME 2003, there are several games that work correctly, such as Mortal Kombat 1, Mortal Kombat 2, and others.

However, there are also some games that fail to run and display this error message, For example:  WWF WrestleMania, Terminator 2: Judgment Day, Ultimate Mortal Kombat 3, Operation Wolf, and many more...

I've attached the log files for the games in MAME 2003 that I mentioned above and are currently showing this error message.

When I restore the core version of mame2003 to 07-01-25, all these games load properly (even with the 4.2.2 build of emulatorjs).

[operation-wolf-1750167989970.log](https://github.com/user-attachments/files/20776992/operation-wolf-1750167989970.log)
[terminator-2-judgment-day-1750168168048.log](https://github.com/user-attachments/files/20776994/terminator-2-judgment-day-1750168168048.log)
[umk-1750168113140.log](https://github.com/user-attachments/files/20776993/umk-1750168113140.log)
[wwf-wrestlemania-1750168439828.log](https://github.com/user-attachments/files/20776991/wwf-wrestlemania-1750168439828.log)

**Comment by ethanaobrien** [comment]
Does mame2003_plus have this same issue?

**Comment by shaylevary** [comment]
mame2003_plus core runs all the games I mentioned earlier properly without the error message, so the problem is only when running the games on mame2003 core.

And regarding the Amiga core, as you mentioned earlier, this error seems to occur specifically with all WHDLoad ROMs.

**Comment by kghorvath** [comment]
Just wanted to share that I'm having the same issue with Amiga. ADF files work, LHA doesn't. I can confirm it happens regardless of what kickstart file is used.

**Comment by ethanaobrien** [comment]
Please confirm this has been fixed: [puae-wasm.zip](https://github.com/user-attachments/files/21668654/puae-wasm.zip)

CC @michael-j-green

**Comment by shaylevary** [comment]
Hi,

First of all, thank you for helping this project i really appreciate you for that.
Secondly, I’m happy to report that the error message issue when running Amiga game has been resolved,.

However, now that the game starts

[emulatorjs-amiga-console-log.txt](https://github.com/user-attachments/files/21674437/emulatorjs-amiga-console-log.txt)

, it starts stuttering in terms of both audio and the game display’s refresh rate.
I’ve attached the console log from running an Amiga game – perhaps you can find the reason why the Amiga emulation is stuttering there.

In any case, thank you for the progress made toward solving this… I truly appreciate it!
Shay

**Comment by ethanaobrien** [comment]
Hey @shaylevary, I'm not entirely sure. It could be due to asyncify (which I very much am hoping to soon remove). Have you tried disabling vsync?

**Comment by shaylevary** [comment]
Hi.
I tried turning off VSync, but that didn’t solve the problem. The sound still stutters and very noisy.
On the other hand, in the older version of puae-wasm.data from 19/08/24 which i'm using, the sound is fine and the gameplay speed is high.

**Comment by michael-j-green** [comment]
> Please confirm this has been fixed: [puae-wasm.zip](https://github.com/user-attachments/files/21668654/puae-wasm.zip)
> 
> CC @michael-j-green 

Hi @ethanaobrien, I'm currently travelling and won't be able to test this until at least Sunday night my time. More likely Monday though.

**Comment by ethanaobrien** [comment]
>On the other hand, in the older version of puae-wasm.data from 19/08/24 which i'm using, the sound is fine and the gameplay speed is high.

This could be due to either asyncify, openal, or possibly that puae has higher hardware requirements now

**Comment by shaylevary** [comment]
BTW, the old puae-wasm I’m using doesn’t work with the latest script version, and likewise, the new version of puae-wasm (which michael-j-green sent here)  doesn’t work with the older versions of scripts.

It seems that the new script version works differently with the core engines, so there’s no compatibility with older versions of cores.

**Comment by ethanaobrien** [comment]
Correct, wait for the next release

**Comment by jk7gr** [comment]
> Correct, wait for the next release

is the corrected in the recent release? I still have the same issue

**Comment by ethanaobrien** [comment]
It's not in the latest release yet, we may do a pre-release soon

**Comment by jk7gr** [comment]
> It's not in the latest release yet, we may do a pre-release soon

It would be great as it is almost a year now since it’s broken.

**Comment by ethanaobrien** [comment]
>It would be great as it is almost a year now since it’s broken.

Please be patient.
