### ISSUE TITLE
[Bug] Genesis Is Broken In 4.3

### ISSUE THREAD

**Issue by S-Coding23** [EmulatorJS/EmulatorJS#1096]
You can confirm this from the demo sites nightly build. SegaMD loads to the RetroArch back-end and SegaMS loads to a solid black screen. 

The issue is caused by the new downloadRom() function here:

```
if (supportedFile !== null) {
                    this.fileName = supportedFile;
                } else {
                    this.fileName = fileNames[0];
                }
if (isoFile !== null && (supportsExt("iso") || supportsExt("cso") || supportsExt("chd") || supportsExt("elf"))) {
    this.fileName = isoFile;
} else if (supportsExt("cue") || supportsExt("ccd") || supportsExt("toc") || supportsExt("m3u")) {
    if (cueFile !== null) {
        this.fileName = cueFile;
    } else if (!disableCue) {
        console.log("Creating CUE file from file list.");
        this.fileName = this.gameManager.createCueFile(fileNames);
    }
}
```
If supportedFile is not null (like for a Genesis .md file), it never gets processed by the final else if block. The this.fileName is assigned a value in an earlier block, but the else if is not always a reliable catch-all for non-disc-based games.

I have confirmed this by editing the block of code like this to test:

```
} else if (isoFile !== null && (supportsExt("iso") || supportsExt("cso") || supportsExt("chd") || supportsExt("elf"))) {
    this.fileName = isoFile;
} else if (supportsExt("cue") || supportsExt("ccd") || supportsExt("toc") || supportsExt("m3u")) {
    if (this.getCore(true) === "segaMD") {
        if (cueFile !== null) {
            this.fileName = cueFile;
        } else {
            this.fileName = supportedFile;
        }
    } else {
        if (cueFile !== null) {
            this.fileName = cueFile;
```

**Comment by zmarteline** [comment]
Current nightly version still not fix this issue.

**Comment by ethanaobrien** [comment]
> Current nightly version still not fix this issue.

That's expected seeing how this issue isnt closed....

**Comment by zmarteline** [comment]
Also, is not only Genesis: Master System and 32X are broken too.

**Comment by ethanaobrien** [comment]
32X is broken for a different reason. It needs a custom linker to work how we need it to

Segams was mentioned in the original issue

**Comment by ethanaobrien** [comment]
I believe this is fixed. Please confirm @S-Coding23

**Comment by zmarteline** [comment]
it is! But i think your fix broke Sega CD games...

**Comment by ethanaobrien** [comment]
Could you expand on that @zmarteline

**Comment by zmarteline** [comment]
Sure:

<img width="391" height="213" alt="Image" src="https://github.com/user-attachments/assets/8dbe56a2-5ba0-4310-aad5-e8fd347770ca" />

<img width="191" height="95" alt="Image" src="https://github.com/user-attachments/assets/d8cc59c2-4698-4e15-9040-4c442b637cf9" />

**Comment by ethanaobrien** [comment]
Could you also provide the directory structure of your rom? Or just the filename if it isn't zipped

**Comment by zmarteline** [comment]
Can't load Sega Cd   .chd roms with lastest version. Works with previous one.

**Comment by ethanaobrien** [comment]
I can work on this later

**Comment by zmarteline** [comment]
ok, need any other info?

**Comment by ethanaobrien** [comment]
Nope, thats all. Thanks for the help

**Comment by ethanaobrien** [comment]
This has been fixed. Nightly builds may take some time to update. Please confirm once they do @zmarteline

**Comment by zmarteline** [comment]
Didn't work with nightly time stamp 2025-Oct-20 21:08:02.

**Comment by ethanaobrien** [comment]
Nightly builds will not build this change for some time.

**Comment by zmarteline** [comment]
ok, As soon as I notice a change I will try. :)

**Comment by zmarteline** [comment]
11h later and the nightly time stamp still the same I tried. I think it was already up to date and still not working...

**Comment by zmarteline** [comment]
By the way, we should open other issue for the problem, since Genesis issue was solved. :)

**Comment by ethanaobrien** [comment]
Nightlies build at utc-0 iirc. Give it 18 more hours and it should work

If they started building before I pushed the change, it won't have caught the change. Give it time.

**Comment by zmarteline** [comment]
It's confirmed... SEGA CD games are loading successfully! Great job!

**Comment by ethanaobrien** [comment]
Nice!

**Comment by S-Coding23** [comment]
> I believe this is fixed. Please confirm [@S-Coding23](https://github.com/S-Coding23)

Sorry, Ive been away on a work trip. I get back Sunday. Thank you for taking care of this!
