### ISSUE TITLE
Gamepad translations

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#626]
How can I translate the labels inside Gamepad  configuration menu (pad directionals, stick directionals, and side buttons)?
I totally forgot this when I was checking the translation...

**Comment by allancoding** [comment]
That seems to be missing. I will try to add later today.

**Comment by allancoding** [comment]
should be fixed in #628

**Comment by zmarteline** [comment]
@allancoding , Please update the pt-br file with mine.
[pt-BR.json.TXT](https://github.com/EmulatorJS/EmulatorJS/files/12391243/pt-BR.json.TXT)

**Comment by allancoding** [comment]
I'll do that tomorrow.
Thanks

**Comment by zmarteline** [comment]
Also, The  joystick and keyboard input result  labels are still missing...
![input](https://github.com/EmulatorJS/EmulatorJS/assets/101960945/8d74544f-e228-42e2-94b7-9f0f7291b3c2)

**Comment by allancoding** [comment]
I will look at this tomorrow

**Comment by ethanaobrien** [comment]
We cannot modify those joystick/key values. They will mess with the backend.

Although you could possibly manage it, if you're careful

**Comment by allancoding** [comment]
@zmarteline Yes this would be hard to change because those are the JavaScript values. How important is this?

**Comment by ethanaobrien** [comment]
@allancoding if you change it in the correct place, it should be fine

**Comment by zmarteline** [comment]
> @zmarteline Yes this would be hard to change because those are the JavaScript values. How important is this?

Really not that important, I just mention to make it as perfect as possible.

**Comment by allancoding** [comment]
@zmarteline this is being fixed in #630
